python -m pip install tensorflow==2.4.1
python -m pip install cython==0.29
python -m pip install luminol==0.4
python -m pip install taos==1.0.1
python -m pip install --no-deps pyodds==1.0.0rc1
python -m pip install matplotlib==3.2.2
python -m pip install requests==2.23.0
python -m pip install tqdm==4.41.1
python -m pip install Keras==2.4.3
python -m pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
python -m pip install numpy==1.19.5
python -m pip install opencv_python==4.1.2.30
python -m pip install pandas==1.1.5
python -m pip install beautifulsoup4==4.9.3
python -m pip install fake_useragent==0.1.11
python -m pip install func_timeout==4.3.5
python -m pip install Pillow==8.1.0
python -m pip install protobuf==3.14.0
python -m pip install scikit_learn==0.24.1
python -m pip install selenium==3.141.0
python -m pip install lxml==4.6.2
python -m pip install ipywidgets==7.6.3
python -m pip install kaleido==0.2.1
python -m pip install seaborn==0.11.1
python -m pip install plotly==4.14.3
python -m pip install ipython==7.16.0
python -m pip install repackage==0.7.3
python -m pip install xmltodict==0.12.0
python -m pip install nltk==3.6.2
python -m pip install setuptools==41.2.0
python -m pip install timm==0.6.11
